# Generated by Django 5.0.1 on 2024-02-08 16:53

import lazy_json_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('eager_data', models.JSONField()),
                ('lazy_data', lazy_json_field.fields.LazyJSONField()),
            ],
        ),
    ]
